services:
  calibre:
    build:
      context: .
      dockerfile: docker/calibre.Dockerfile
    volumes:
      - cache:/app/cache
      - tmp:/app/tmp
    network_mode: host

  app:
    build: .
    network_mode: host
    environment:
      DATABASE_URL: postgres://fichub:fichub@localhost:5432/fichub
      REDIS_URL: redis://localhost:6379
      CACHE_DIR: /app/cache
      TMP_DIR: /app/tmp
      CALIBRE_CONTAINER: calibre
      PORT: 8004
      FRONTEND_DIR: /app/frontend
      RUST_LOG: info,fichub=debug
      JWT_SECRET: bbcc90f26b1985701d4e0e183d1013e747995ad7f9f06482fd7a9a0f72c105750ad4a5ec8ba610babd13f9031458064883574318477d92130a1764c19ce9a6cc
    volumes:
      - cache:/app/cache
      - tmp:/app/tmp
    depends_on:
      - calibre

volumes:
  cache:
  tmp:
