//! Honeypot fields + form-timing traps — silent rejection of
//! human-impersonation bots on user-facing forms (registration, comments).
//!
//! The whole point is to stay invisible: a bot that fills the hidden
//! `website` honeypot or submits in under `MIN_FORM_MS` gets a normal,
//! success-looking response, but nothing is persisted. This never teaches
//! the bot that it was caught, and never challenges a real user.

use std::time::Duration;

/// Hidden honeypot input name shared by the frontend forms and the backend
/// checks. Both register and comment forms render a CSS-hidden `<input
/// name="website">`; any non-empty value means a bot filled it (humans
/// never see it).
pub const HONEYPOT_FIELD: &str = "website";

/// Hidden form-open timestamp field. The frontend sets
/// `form_opened_at` (epoch ms, `Date.now()`) when the form mounts;
/// the backend uses it to measure how long the form was open before
/// submission.
pub const OPENED_AT_FIELD: &str = "form_opened_at";

/// Submissions that claim the form was open for less than this are
/// rejected silently — a human cannot type a comment or fill a
/// registration form that fast. The frontend forms never submit this
/// early, so no legitimate user is ever affected.
pub const MIN_FORM_MS: u64 = 500;

/// Maximum accepted age of the `form_opened_at` timestamp. Clock skew,
/// cached pages, or a stale timestamp are all bot-ish signals.
pub const MAX_FORM_AGE_MS: u64 = 60 * 60 * 1000; // 1 hour

/// Result of the honeypot/timing inspection.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TrapVerdict {
    /// Passed all checks — proceed with the real handler.
    Clean,
    /// Honeypot field was filled, or the form was submitted impossibly
    /// fast. Caller must silently swallow the submission (return a
    /// success-looking response, create nothing).
    RejectSilently,
}

/// Inspect a parsed form submission for bot traps.
///
/// * `website` — if non-empty, the honeypot was triggered. Reject.
/// * `form_opened_at` — if absent, the submission did not come from the
///   frontend form (curl / scripted client). Reject (bots script the API
///   directly and skip the JS-set field).
/// * `form_opened_at` — if present but elapsed time is under
///   [`MIN_FORM_MS`], or the timestamp is absurdly old (> 1h), reject.
///
/// Everything else passes as [`TrapVerdict::Clean`].
pub fn inspect_submission(
    website: Option<&str>,
    form_opened_at: Option<&str>,
    now_ms: u64,
) -> TrapVerdict {
    // Honeypot: any non-empty value means a bot filled a field no human
    // can see.
    if website.map(|w| !w.trim().is_empty()).unwrap_or(false) {
        return TrapVerdict::RejectSilently;
    }

    // Timing trap. Absence of the JS-set field means the submission was
    // not made through the real form.
    let opened_at: u64 = match form_opened_at {
        Some(raw) => match raw.trim().parse() {
            Ok(ms) => ms,
            // Unparsable — not generated by our frontend.
            Err(_) => return TrapVerdict::RejectSilently,
        },
        None => return TrapVerdict::RejectSilently,
    };

    // Absurdly old timestamps (cached/stale) are not human typing.
    if now_ms.saturating_sub(opened_at) > MAX_FORM_AGE_MS {
        return TrapVerdict::RejectSilently;
    }

    // Impossibly fast submission.
    let elapsed = Duration::from_millis(now_ms.saturating_sub(opened_at));
    if elapsed < Duration::from_millis(MIN_FORM_MS) {
        return TrapVerdict::RejectSilently;
    }

    TrapVerdict::Clean
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn clean_submission_passes() {
        // Form was "opened" 5 seconds ago, honeypot empty.
        let now = 1_700_000_000_000u64;
        assert_eq!(
            inspect_submission(Some(""), Some(&(now - 5_000).to_string()), now),
            TrapVerdict::Clean
        );
    }

    #[test]
    fn honeypot_filled_is_rejected() {
        let now = 1_700_000_000_000u64;
        // Even with a plausible open time, a filled honeypot is a bot.
        assert_eq!(
            inspect_submission(
                Some("http://spam.example"),
                Some(&(now - 5_000).to_string()),
                now
            ),
            TrapVerdict::RejectSilently
        );
        // Whitespace-only honeypot is treated as empty (bots that trim still pass).
        assert_eq!(
            inspect_submission(Some("   "), Some(&(now - 5_000).to_string()), now),
            TrapVerdict::Clean
        );
    }

    #[test]
    fn missing_opened_at_is_rejected() {
        let now = 1_700_000_000_000u64;
        // Direct API scripting (curl, no JS) never sets form_opened_at.
        assert_eq!(
            inspect_submission(Some(""), None, now),
            TrapVerdict::RejectSilently
        );
        // Empty-string timestamp is equally missing.
        assert_eq!(
            inspect_submission(Some(""), Some(""), now),
            TrapVerdict::RejectSilently
        );
    }

    #[test]
    fn too_fast_submission_is_rejected() {
        let now = 1_700_000_000_000u64;
        // 100ms after "open" — impossible for a human.
        assert_eq!(
            inspect_submission(Some(""), Some(&(now - 100).to_string()), now),
            TrapVerdict::RejectSilently
        );
        // Exactly at the 500ms boundary: 499ms is still too fast.
        assert_eq!(
            inspect_submission(Some(""), Some(&(now - 499).to_string()), now),
            TrapVerdict::RejectSilently
        );
        // 500ms exactly is allowed.
        assert_eq!(
            inspect_submission(Some(""), Some(&(now - 500).to_string()), now),
            TrapVerdict::Clean
        );
    }

    #[test]
    fn stale_timestamp_is_rejected() {
        let now = 1_700_000_000_000u64;
        // "Opened" 2 hours ago — cached page / replayed request.
        assert_eq!(
            inspect_submission(Some(""), Some(&(now - 2 * 60 * 60 * 1000).to_string()), now),
            TrapVerdict::RejectSilently
        );
    }

    #[test]
    fn garbage_timestamp_is_rejected() {
        let now = 1_700_000_000_000u64;
        assert_eq!(
            inspect_submission(Some(""), Some("not-a-timestamp"), now),
            TrapVerdict::RejectSilently
        );
    }

    #[test]
    fn future_timestamp_is_rejected_as_stale() {
        // opened_at in the future: saturating_sub gives 0 → too fast.
        let now = 1_700_000_000_000u64;
        assert_eq!(
            inspect_submission(Some(""), Some(&(now + 10_000).to_string()), now),
            TrapVerdict::RejectSilently
        );
    }
}
