use std::fs;
use std::io::{BufWriter, Write};
use std::path::{Path, PathBuf};

use docx_rs::{Docx, Paragraph, Run, AlignmentType};
use md5::{Digest, Md5};
use uuid::Uuid;

use crate::export::ExportError;
use crate::scrape::{Chapter, FicMetadata};

/// Generate a Word (.docx) export for the given fic metadata and chapters.
///
/// Title/author/status lines are added as styled paragraphs, chapter content
/// is converted from HTML to plain text (paragraphs become separate docx
/// paragraphs), and the result is packed into a real OOXML zip.
///
/// Returns `(docx_path, md5_hex)`.
pub async fn create_docx(
    meta: &FicMetadata,
    chapters: &[Chapter],
    tmp_dir: &Path,
) -> Result<(PathBuf, String), ExportError> {
    let uuid = Uuid::new_v4();
    let work_dir = tmp_dir.join(uuid.to_string());
    fs::create_dir_all(&work_dir)?;

    // ---- document ---------------------------------------------------------
    let mut doc = Docx::new();

    // Title
    doc = doc.add_paragraph(
        Paragraph::new()
            .align(AlignmentType::Center)
            .size(32)
            .bold()
            .add_run(Run::new().size(32).bold().add_text(&meta.title)),
    );
    // Author
    doc = doc.add_paragraph(
        Paragraph::new()
            .align(AlignmentType::Center)
            .size(24)
            .add_run(Run::new().size(24).italic().add_text(format!("by {}", meta.author))),
    );
    // Stats line
    doc = doc.add_paragraph(
        Paragraph::new()
            .align(AlignmentType::Center)
            .size(18)
            .add_run(Run::new().size(18).add_text(format!(
                "Words: {} | Chapters: {} | Status: {}",
                meta.words, meta.chapters, meta.status
            ))),
    );
    doc = doc.add_paragraph(
        Paragraph::new()
            .align(AlignmentType::Center)
            .size(18)
            .add_run(Run::new().size(18).add_text(format!(
                "Published: {} | Updated: {}",
                format_timestamp(meta.published),
                format_timestamp(meta.updated),
            ))),
    );
    doc = doc.add_paragraph(Paragraph::new()); // spacer

    // Description
    for para in html_to_paragraphs(&meta.desc) {
        doc = doc.add_paragraph(
            Paragraph::new().add_run(Run::new().add_text(para)),
        );
    }

    // Source footer
    doc = doc.add_paragraph(
        Paragraph::new()
            .add_run(Run::new().italic().add_text(format!(
                "Generated by fICHub — {}",
                meta.source
            ))),
    );
    doc = doc.add_paragraph(Paragraph::new()); // spacer

    // ---- chapters ---------------------------------------------------------
    for chapter in chapters {
        doc = doc.add_paragraph(
            Paragraph::new()
                .size(28)
                .bold()
                .add_run(Run::new().size(28).bold().add_text(&chapter.title)),
        );
        doc = doc.add_paragraph(Paragraph::new()); // spacer
        for para in html_to_paragraphs(&chapter.content) {
            doc = doc.add_paragraph(
                Paragraph::new().add_run(Run::new().add_text(para)),
            );
        }
        doc = doc.add_paragraph(Paragraph::new()); // spacer
    }

    // ---- write ------------------------------------------------------------
    let docx_path = work_dir.join("output.docx");
    let file = fs::File::create(&docx_path)?;
    let mut writer = BufWriter::new(file);
    doc.pack(&mut writer).map_err(|e| ExportError::ZipError(e.to_string()))?;
    writer.flush().map_err(|e| ExportError::IoError(e.to_string()))?;

    let data = fs::read(&docx_path)?;
    let md5_hex = Md5::digest(&data)
        .iter()
        .map(|b| format!("{:02x}", b))
        .collect::<String>();

    Ok((docx_path, md5_hex))
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Convert HTML to a list of plain-text paragraphs.
///
/// Block-level tags (`<p>`, `<h1>`–`<h6>`, `<div>`, `<br>`, `<li>`) delimit
/// paragraphs; inline tags are stripped; HTML entities are decoded.
fn html_to_paragraphs(input: &str) -> Vec<String> {
    use regex_lite::Regex;

    // Replace block-level boundaries with newlines.
    let block_re =
        Regex::new(r"(?i)</?(?:p|div|h[1-6]|li|tr)[^>]*>|<br\s*/?>").unwrap();
    let s = block_re.replace_all(input, "\n");

    // Strip all remaining tags.
    let tag_re = Regex::new(r"<[^>]+>").unwrap();
    let s = tag_re.replace_all(&s, "");
    let s = decode_entities(&s);

    // Split into paragraphs, collapse whitespace per line, drop empties.
    s.split('\n')
        .map(|line| {
            line.split_whitespace()
                .collect::<Vec<&str>>()
                .join(" ")
        })
        .filter(|line| !line.is_empty())
        .collect()
}

/// Decode common HTML entities to their plain-text equivalents.
fn decode_entities(input: &str) -> String {
    let mut s = input.to_string();
    s = s.replace("&amp;", "&");
    s = s.replace("&lt;", "<");
    s = s.replace("&gt;", ">");
    s = s.replace("&quot;", "\"");
    s = s.replace("&#39;", "'");
    s = s.replace("&apos;", "'");
    s = s.replace("&#x27;", "'");
    s = s.replace("&#x2F;", "/");
    s = s.replace("&nbsp;", " ");
    s = s.replace("&#xA;", "\n");
    s = s.replace("&#10;", "\n");
    s
}

fn format_timestamp(unix_millis: i64) -> String {
    use chrono::DateTime;

    let secs = unix_millis / 1000;
    let nsecs = ((unix_millis % 1000) * 1_000_000) as u32;

    DateTime::from_timestamp(secs, nsecs)
        .map(|dt| dt.format("%Y-%m-%d").to_string())
        .unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_meta() -> FicMetadata {
        FicMetadata {
            url_id: "test123".into(),
            title: "Test Fic".into(),
            author: "Test Author".into(),
            chapters: 1,
            words: 1000,
            desc: "<p>A great story</p>".into(),
            published: 1700000000000,
            updated: 1700000000000,
            status: "complete".into(),
            source: "https://example.com/fiction/123".into(),
            source_id: 1,
            author_id: 42,
            author_url: "https://example.com/u/test".into(),
            author_local_id: "test".into(),
            content_hash: None,
            extra_meta: None,
            raw_extended_meta: None,
        }
    }

    fn make_chapters() -> Vec<Chapter> {
        vec![Chapter {
            chapter_id: 1,
            title: "Chapter One".into(),
            content: "<p>Hello <b>world</b>.</p><p>Second paragraph.</p>".into(),
        }]
    }

    #[test]
    fn test_html_to_paragraphs_basic() {
        let input = "<p>First.</p><p>Second.</p>";
        assert_eq!(html_to_paragraphs(input), vec!["First.", "Second."]);
    }

    #[test]
    fn test_html_to_paragraphs_strips_inline() {
        let input = "<p>Hello <em>world</em> &amp; friends</p>";
        assert_eq!(html_to_paragraphs(input), vec!["Hello world & friends"]);
    }

    #[test]
    fn test_html_to_paragraphs_headers_and_br() {
        let input = "<h1>Title</h1><p>Line one<br/>Line two</p>";
        assert_eq!(
            html_to_paragraphs(input),
            vec!["Title", "Line one", "Line two"]
        );
    }

    #[test]
    fn test_html_to_paragraphs_empty() {
        assert!(html_to_paragraphs("").is_empty());
        assert!(html_to_paragraphs("<p></p>").is_empty());
    }

    #[test]
    fn test_html_to_paragraphs_whitespace_collapse() {
        let input = "<p>   Lots   of   spaces   </p>";
        assert_eq!(html_to_paragraphs(input), vec!["Lots of spaces"]);
    }

    #[test]
    fn test_create_docx_produces_valid_zip() {
        let tmp = std::env::temp_dir().join("fichub_test_docx");
        let _ = std::fs::remove_dir_all(&tmp);
        std::fs::create_dir_all(&tmp).unwrap();

        let rt = tokio::runtime::Runtime::new().unwrap();
        let (path, md5_hex) = rt
            .block_on(create_docx(&make_meta(), &make_chapters(), &tmp))
            .unwrap();

        assert!(path.exists());
        assert_eq!(md5_hex.len(), 32);

        // Must be a valid zip containing the OOXML document part.
        let file = std::fs::File::open(&path).unwrap();
        let mut archive = zip::ZipArchive::new(file).unwrap();
        let names: Vec<String> = archive.file_names().map(|s| s.to_string()).collect();
        assert!(
            names.iter().any(|n| n == "word/document.xml"),
            "docx must contain word/document.xml, got {names:?}"
        );

        let mut doc_xml = String::new();
        use std::io::Read;
        archive
            .by_name("word/document.xml")
            .unwrap()
            .read_to_string(&mut doc_xml)
            .unwrap();
        assert!(doc_xml.contains("Test Fic"));
        assert!(doc_xml.contains("Chapter One"));
        assert!(doc_xml.contains("Hello"));
        assert!(doc_xml.contains("world"));

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn test_create_docx_md5_stable_for_same_input() {
        let tmp = std::env::temp_dir().join("fichub_test_docx_md5");
        let _ = std::fs::remove_dir_all(&tmp);
        std::fs::create_dir_all(&tmp).unwrap();

        let rt = tokio::runtime::Runtime::new().unwrap();
        let (_, md5_a) = rt
            .block_on(create_docx(&make_meta(), &make_chapters(), &tmp))
            .unwrap();
        let (_, md5_b) = rt
            .block_on(create_docx(&make_meta(), &make_chapters(), &tmp))
            .unwrap();
        assert_eq!(md5_a, md5_b, "same input must produce same md5");

        let _ = std::fs::remove_dir_all(&tmp);
    }
}
