use std::fs;
use std::path::{Path, PathBuf};

use md5::{Digest, Md5};
use uuid::Uuid;

use crate::export::ExportError;
use crate::scrape::{Chapter, FicMetadata};

/// Generate a Markdown export for the given fic metadata and chapters.
///
/// Returns `(md_path, md5_hex)`.
pub async fn create_md(
    meta: &FicMetadata,
    chapters: &[Chapter],
    tmp_dir: &Path,
) -> Result<(PathBuf, String), ExportError> {
    let uuid = Uuid::new_v4();
    let work_dir = tmp_dir.join(uuid.to_string());
    fs::create_dir_all(&work_dir)?;

    let mut output = String::new();

    // ---- header -----------------------------------------------------------
    output.push_str(&format!("# {}\n\n", meta.title));
    output.push_str(&format!("**by {}**\n\n", meta.author));
    output.push_str(&format!(
        "Words: {} | Chapters: {} | Status: {}  \n",
        meta.words, meta.chapters, meta.status,
    ));
    output.push_str(&format!(
        "Published: {} | Updated: {}\n\n",
        format_timestamp(meta.published),
        format_timestamp(meta.updated),
    ));

    if !meta.desc.is_empty() {
        output.push_str(&html_to_md(&meta.desc));
        output.push_str("\n\n");
    }

    output.push_str(&format!(
        "---\n\n*Generated by fICHub — {}*\n\n---\n\n",
        meta.source,
    ));

    // ---- chapters ---------------------------------------------------------
    for chapter in chapters {
        output.push_str(&format!("## {}\n\n", chapter.title));
        output.push_str(&html_to_md(&chapter.content));
        output.push_str("\n\n");
    }

    let md_path = work_dir.join("output.md");
    fs::write(&md_path, output.as_bytes())?;

    let data = fs::read(&md_path)?;
    let md5_hex = Md5::digest(&data)
        .iter()
        .map(|b| format!("{:02x}", b))
        .collect::<String>();

    Ok((md_path, md5_hex))
}

// ---------------------------------------------------------------------------
// HTML → Markdown converter (regex-based, simple and reliable)
// ---------------------------------------------------------------------------

/// Convert HTML to Markdown using sequential regex replacements.
fn html_to_md(input: &str) -> String {
    let s = decode_entities(input);

    // Block-level: replace with markdown equivalents
    let s = regex_replace(r"(?i)<h1[^>]*>(.*?)</h1>", &s, "# $1");
    let s = regex_replace(r"(?i)<h2[^>]*>(.*?)</h2>", &s, "## $1");
    let s = regex_replace(r"(?i)<h3[^>]*>(.*?)</h3>", &s, "### $1");
    let s = regex_replace(r"(?i)<h4[^>]*>(.*?)</h4>", &s, "#### $1");
    let s = regex_replace(r"(?i)<h5[^>]*>(.*?)</h5>", &s, "##### $1");
    let s = regex_replace(r"(?i)<h6[^>]*>(.*?)</h6>", &s, "###### $1");

    // Blockquotes
    let s = regex_replace(r"(?i)<blockquote[^>]*>(.*?)</blockquote>", &s, "> $1");

    // List items
    let s = regex_replace(r"(?i)<li[^>]*>(.*?)</li>", &s, "- $1");

    // Horizontal rules
    let s = regex_replace(r"(?i)<hr\s*/?>", &s, "\n---\n");

    // Line breaks
    let s = regex_replace(r"(?i)<br\s*/?>", &s, "\n");

    // Paragraphs and divs → double newline
    let s = regex_replace(r"(?i)</p>", &s, "\n\n");
    let s = regex_replace(r"(?i)</div>", &s, "\n\n");

    // Inline: bold (separate patterns to avoid backreferences)
    let s = regex_replace(r"(?i)<b[^>]*>(.*?)</b>", &s, "**$1**");
    let s = regex_replace(r"(?i)<strong[^>]*>(.*?)</strong>", &s, "**$1**");

    // Inline: italic (separate patterns to avoid backreferences)
    let s = regex_replace(r"(?i)<i[^>]*>(.*?)</i>", &s, "*$1*");
    let s = regex_replace(r"(?i)<em[^>]*>(.*?)</em>", &s, "*$1*");

    // Inline: links
    let s = regex_replace(
        r#"(?i)<a[^>]*href="([^"]*)"[^>]*>(.*?)</a>"#,
        &s,
        "[$2]($1)",
    );
    let s = regex_replace(
        r#"(?i)<a[^>]*href='([^']*)'[^>]*>(.*?)</a>"#,
        &s,
        "[$2]($1)",
    );

    // Images
    let s = regex_replace(
        r#"(?i)<img[^>]*src="([^"]*)"[^>]*alt="([^"]*)"[^>]*/?>"#,
        &s,
        "![$2]($1)",
    );
    let s = regex_replace(
        r#"(?i)<img[^>]*alt="([^"]*)"[^>]*src="([^"]*)"[^>]*/?>"#,
        &s,
        "![$1]($2)",
    );
    let s = regex_replace(r#"(?i)<img[^>]*src="([^"]*)"[^>]*/?>"#, &s, "![]($1)");

    // Remove remaining HTML tags
    let s = regex_replace(
        r"(?i)</?(?:p|div|span|br|hr|table|thead|tbody|tr|td|th|ul|ol|dl|dt|dd|figure|figcaption|section|article|header|footer|nav|aside|main|details|summary|pre|code|tt|small|sub|sup|u|s|del|ins|mark|abbr|cite|q|var|kbd|samp|dfn|time|address|bdi|bdo|ruby|rt|rp|wbr)[^>]*>",
        &s,
        "",
    );

    // Remove any remaining tags
    let s = regex_replace(r"<[^>]+>", &s, "");

    // Collapse whitespace within lines (preserve newlines)
    let s = regex_replace(r"[^\S\n]+", &s, " ");

    // Collapse 3+ newlines to 2
    let s = regex_replace(r"\n{3,}", &s, "\n\n");

    s.trim().to_string()
}

/// Simple regex replacement using the regex_lite crate.
fn regex_replace(pattern: &str, input: &str, replacement: &str) -> String {
    let re = regex_lite::Regex::new(pattern).unwrap();
    let mut result = String::with_capacity(input.len());
    let mut last_end = 0;

    for caps in re.captures_iter(input) {
        let m = caps.get(0).unwrap();
        result.push_str(&input[last_end..m.start()]);
        // Replace $1, $2, etc. with capture group values
        let mut rep = replacement.to_string();
        for i in 1..caps.len() {
            if let Some(group) = caps.get(i) {
                rep = rep.replace(&format!("${}", i), group.as_str());
            }
        }
        result.push_str(&rep);
        last_end = m.end();
    }
    result.push_str(&input[last_end..]);
    result
}

/// Decode common HTML entities.
fn decode_entities(input: &str) -> String {
    let mut s = input.to_string();
    s = s.replace("&amp;", "&");
    s = s.replace("&lt;", "<");
    s = s.replace("&gt;", ">");
    s = s.replace("&quot;", "\"");
    s = s.replace("&#39;", "'");
    s = s.replace("&apos;", "'");
    s = s.replace("&#x27;", "'");
    s = s.replace("&#x2F;", "/");
    s = s.replace("&nbsp;", " ");
    s = s.replace("&#xA;", "\n");
    s = s.replace("&#10;", "\n");
    s
}

fn format_timestamp(unix_millis: i64) -> String {
    use chrono::DateTime;

    let secs = unix_millis / 1000;
    let nsecs = ((unix_millis % 1000) * 1_000_000) as u32;

    DateTime::from_timestamp(secs, nsecs)
        .map(|dt| dt.format("%Y-%m-%d").to_string())
        .unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_html_to_md_headers() {
        let input = "<h1>Title</h1><h2>Subtitle</h2><h3>Section</h3>";
        let result = html_to_md(input);
        assert!(result.contains("# Title"));
        assert!(result.contains("## Subtitle"));
        assert!(result.contains("### Section"));
    }

    #[test]
    fn test_html_to_md_paragraphs() {
        let input = "<p>First paragraph.</p><p>Second paragraph.</p>";
        let result = html_to_md(input);
        assert!(result.contains("First paragraph."));
        assert!(result.contains("Second paragraph."));
        assert!(!result.contains("<p>"));
    }

    #[test]
    fn test_html_to_md_bold_italic() {
        let input = "<p>This is <b>bold</b> and <i>italic</i> text.</p>";
        let result = html_to_md(input);
        assert!(
            result.contains("**bold**"),
            "Expected **bold** in: {}",
            result
        );
        assert!(
            result.contains("*italic*"),
            "Expected *italic* in: {}",
            result
        );
    }

    #[test]
    fn test_html_to_md_links() {
        let input = r#"<p>Visit <a href="https://example.com">Example</a></p>"#;
        let result = html_to_md(input);
        assert!(
            result.contains("[Example](https://example.com)"),
            "Expected link in: {}",
            result
        );
    }

    #[test]
    fn test_html_to_md_blockquote() {
        let input = "<blockquote>This is a quote.</blockquote>";
        let result = html_to_md(input);
        assert!(result.contains("> This is a quote."));
    }

    #[test]
    fn test_html_to_md_lists() {
        let input = "<ul><li>Item 1</li><li>Item 2</li></ul>";
        let result = html_to_md(input);
        assert!(result.contains("- Item 1"));
        assert!(result.contains("- Item 2"));
    }

    #[test]
    fn test_html_to_md_br() {
        let input = "Line 1<br>Line 2<br/>Line 3<br />";
        let result = html_to_md(input);
        assert!(result.contains("Line 1\nLine 2\nLine 3"));
    }

    #[test]
    fn test_html_to_md_hr() {
        let input = "<p>Before</p><hr><p>After</p>";
        let result = html_to_md(input);
        assert!(result.contains("---"));
    }

    #[test]
    fn test_html_to_md_entities() {
        let input = "<p>Tom &amp; Jerry &lt;3</p>";
        let result = html_to_md(input);
        assert!(result.contains("Tom & Jerry <3"));
    }

    #[test]
    fn test_html_to_md_images() {
        let input = r#"<img src="https://example.com/image.png" alt="Cover">"#;
        let result = html_to_md(input);
        assert!(
            result.contains("![Cover](https://example.com/image.png)"),
            "Expected image in: {}",
            result
        );
    }

    #[test]
    fn test_html_to_md_empty() {
        assert_eq!(html_to_md(""), "");
        assert_eq!(html_to_md("<p></p>"), "");
    }

    #[test]
    fn test_html_to_md_complex() {
        let input = r#"<div class="chapter">
            <h2>Chapter 1</h2>
            <p>It was a <em>dark</em> and <strong>stormy</strong> night.</p>
            <p>She said "hello" &amp; he waved.</p>
        </div>"#;
        let result = html_to_md(input);
        assert!(
            result.contains("## Chapter 1"),
            "Missing header in: {}",
            result
        );
        assert!(result.contains("*dark*"), "Missing italic in: {}", result);
        assert!(result.contains("**stormy**"), "Missing bold in: {}", result);
        assert!(result.contains("She said \"hello\" & he waved."));
    }

    #[test]
    fn test_format_timestamp_valid() {
        // 2023-01-15 00:00:00 UTC = 1673740800000 millis
        let result = format_timestamp(1673740800000);
        assert_eq!(result, "2023-01-15");
    }

    #[test]
    fn test_format_timestamp_zero() {
        let result = format_timestamp(0);
        assert_eq!(result, "1970-01-01");
    }
}
