use std::fs;
use std::path::{Path, PathBuf};

use md5::{Digest, Md5};
use uuid::Uuid;

use crate::export::ExportError;
use crate::scrape::{Chapter, FicMetadata};

/// Generate a plain-text export for the given fic metadata and chapters.
///
/// Strips all HTML tags from chapter content, decodes HTML entities,
/// and produces clean text with chapters separated by double newlines.
///
/// Returns `(txt_path, md5_hex)`.
pub async fn create_txt(
    meta: &FicMetadata,
    chapters: &[Chapter],
    tmp_dir: &Path,
) -> Result<(PathBuf, String), ExportError> {
    let uuid = Uuid::new_v4();
    let work_dir = tmp_dir.join(uuid.to_string());
    fs::create_dir_all(&work_dir)?;

    let mut output = String::new();

    // ---- header -----------------------------------------------------------
    output.push_str(&format!("{}\n", meta.title));
    output.push_str(&format!("by {}\n", meta.author));
    output.push_str(&format!(
        "Words: {} | Chapters: {} | Status: {}\n",
        meta.words, meta.chapters, meta.status,
    ));
    output.push_str(&format!(
        "Published: {} | Updated: {}\n",
        format_timestamp(meta.published),
        format_timestamp(meta.updated),
    ));

    if !meta.desc.is_empty() {
        output.push_str("\n");
        output.push_str(&strip_html(&meta.desc));
        output.push_str("\n");
    }

    output.push_str(&format!(
        "\n---\nGenerated by fICHub — {}\n---\n",
        meta.source,
    ));

    // ---- chapters ---------------------------------------------------------
    for chapter in chapters {
        output.push_str("\n");
        output.push_str(&format!("=== {} ===\n", chapter.title));
        output.push_str("\n");

        let text = strip_html(&chapter.content);
        output.push_str(&text);
        output.push_str("\n");
    }

    let txt_path = work_dir.join("output.txt");
    fs::write(&txt_path, output.as_bytes())?;

    let data = fs::read(&txt_path)?;
    let md5_hex = Md5::digest(&data)
        .iter()
        .map(|b| format!("{:02x}", b))
        .collect::<String>();

    Ok((txt_path, md5_hex))
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Strip HTML tags from a string, decoding common HTML entities, and collapse
/// whitespace to produce clean plain text.
///
/// Block-level tags (`<p>`, `<h1>`–`<h6>`, `<div>`, `<br>`) are replaced with
/// newlines so that paragraph structure is preserved. The order of operations
/// is: (1) replace block tags with newlines, (2) strip remaining tags,
/// (3) decode entities, (4) collapse whitespace.
fn strip_html(input: &str) -> String {
    use regex_lite::Regex;

    // Step 1: Replace block-level opening/closing tags with double newlines.
    // We use a regex to match tags like <p>, </p>, <br/>, <br>, <h1>...</h6>,
    // </h1>...</h6>, <div>, </div>.
    let block_re = Regex::new(r"(?i)</?(?:p|div|h[1-6])[^>]*>|<br\s*/?>").unwrap();
    let s = block_re.replace_all(input, "\n\n");

    // Step 2: Strip all remaining tags.
    let tag_re = Regex::new(r"<[^>]+>").unwrap();
    let s = tag_re.replace_all(&s, "");
    let mut result = s.to_string();

    // Step 3: Decode HTML entities (AFTER tag stripping, so `<3` in text is safe).
    result = decode_entities(&result);

    // Step 4: Collapse whitespace — split on newlines, trim each line, join.
    let lines: Vec<String> = result
        .split('\n')
        .map(|line| {
            line.split_whitespace()
                .collect::<Vec<&str>>()
                .join(" ")
        })
        .collect();
    let mut cleaned = lines.join("\n");

    // Collapse 3+ consecutive newlines into exactly 2.
    while cleaned.contains("\n\n\n") {
        cleaned = cleaned.replace("\n\n\n", "\n\n");
    }

    // Trim leading/trailing whitespace from the whole result
    let cleaned = cleaned.trim().to_string();
    cleaned
}

/// Decode common HTML entities to their plain-text equivalents.
fn decode_entities(input: &str) -> String {
    let mut s = input.to_string();
    s = s.replace("&amp;", "&");
    s = s.replace("&lt;", "<");
    s = s.replace("&gt;", ">");
    s = s.replace("&quot;", "\"");
    s = s.replace("&#39;", "'");
    s = s.replace("&apos;", "'");
    s = s.replace("&#x27;", "'");
    s = s.replace("&#x2F;", "/");
    s = s.replace("&nbsp;", " ");
    s = s.replace("&#xA;", "\n");
    s = s.replace("&#10;", "\n");
    s
}

fn format_timestamp(unix_millis: i64) -> String {
    use chrono::DateTime;

    let secs = unix_millis / 1000;
    let nsecs = ((unix_millis % 1000) * 1_000_000) as u32;

    DateTime::from_timestamp(secs, nsecs)
        .map(|dt| dt.format("%Y-%m-%d").to_string())
        .unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_strip_html_basic_paragraphs() {
        let input = "<p>First paragraph.</p><p>Second paragraph.</p>";
        let result = strip_html(input);
        assert_eq!(result, "First paragraph.\n\nSecond paragraph.");
    }

    #[test]
    fn test_strip_html_headers() {
        let input = "<h1>Title</h1><p>Content</p>";
        let result = strip_html(input);
        assert!(result.contains("Title"));
        assert!(result.contains("Content"));
        assert!(!result.contains("<h1>"));
        assert!(!result.contains("<p>"));
    }

    #[test]
    fn test_strip_html_br_tags() {
        let input = "Line one<br/>Line two";
        let result = strip_html(input);
        assert_eq!(result, "Line one\n\nLine two");
    }

    #[test]
    fn test_strip_html_entities() {
        let input = "<p>Tom &amp; Jerry &lt;3 &quot;quoted&quot;</p>";
        let result = strip_html(input);
        assert_eq!(result, "Tom & Jerry <3 \"quoted\"");
    }

    #[test]
    fn test_strip_html_complex() {
        let input = r#"<div class="chapter">
            <h2>Chapter 1</h2>
            <p>It was a <em>dark</em> and stormy night.</p>
            <p>She said "hello" &amp; he waved.</p>
        </div>"#;
        let result = strip_html(input);
        assert!(result.contains("Chapter 1"));
        assert!(result.contains("dark"));
        assert!(result.contains("stormy night"));
        assert!(result.contains("She said \"hello\" & he waved."));
        assert!(!result.contains('<'));
    }

    #[test]
    fn test_strip_html_empty() {
        assert_eq!(strip_html(""), "");
        assert_eq!(strip_html("<p></p>"), "");
    }

    #[test]
    fn test_strip_html_nested_tags() {
        let input = "<div><p>Hello <b>world</b></p></div>";
        let result = strip_html(input);
        assert_eq!(result, "Hello world");
    }

    #[test]
    fn test_decode_entities_nbsp() {
        let input = "word1&nbsp;word2";
        let result = decode_entities(input);
        assert_eq!(result, "word1 word2");
    }

    #[test]
    fn test_decode_entities_apos() {
        let input = "it&apos;s a test";
        let result = decode_entities(input);
        assert_eq!(result, "it's a test");
    }

    #[test]
    fn test_format_timestamp_valid() {
        // 2023-01-15 12:00:00 UTC = 1673774400000 millis
        let result = format_timestamp(1673774400000);
        assert_eq!(result, "2023-01-15");
    }

    #[test]
    fn test_format_timestamp_zero() {
        // Unix epoch
        let result = format_timestamp(0);
        assert_eq!(result, "1970-01-01");
    }

    #[test]
    fn test_format_timestamp_negative() {
        // Before epoch
        let result = format_timestamp(-86400000);
        assert_eq!(result, "1969-12-31");
    }

    #[test]
    fn test_strip_html_only_whitespace() {
        let input = "   \n  \n  ";
        let result = strip_html(input);
        assert_eq!(result, "");
    }

    #[test]
    fn test_strip_html_preserves_content() {
        let input = "<p>The quick brown fox jumps over the lazy dog.</p>";
        let result = strip_html(input);
        assert_eq!(
            result,
            "The quick brown fox jumps over the lazy dog."
        );
    }

    #[test]
    fn test_strip_html_multiple_block_levels() {
        let input = "<h1>Title</h1><p>Para 1</p><p>Para 2</p><h2>Subtitle</h2><p>Para 3</p>";
        let result = strip_html(input);
        assert!(result.contains("Title"));
        assert!(result.contains("Para 1"));
        assert!(result.contains("Subtitle"));
        assert!(result.contains("Para 3"));
    }
}
