#!/usr/bin/env python3
"""Feature inventory for FicHub: user-listed features with implementation status.

Each entry: title, implemented (bool or None=unknown), notes, priority hint,
category. Used to (1) score and merge into the ranked CSV, (2) seed
feature_clusters so users can vote on them, (3) pick top unimplemented
features for the kanban triage card.
"""
FEATURES = [
    # --- From the "Engineering Addictiveness" plan ---
    {"title": "Trope Chaining: 'Continue the Vibe' carousel after finishing/bookmarking a fic",
     "impl": True, "note": "Trope browser + rabbit-hole recs shipped (tropes route, similar fics)", "cat": "discovery"},
    {"title": "Blind Date with a Fic: discovery button hiding title/fandom, showing only summary+word count+tropes",
     "impl": False, "note": "Not found in code", "cat": "discovery"},
    {"title": "Reading Streaks: track consecutive days read/download, flame icon in navbar",
     "impl": True, "note": "login_streaks table + quests.rs streak handling", "cat": "retention"},
    {"title": "Milestones: 'You've read 1.2M words this year' + top-X% reader notifications",
     "impl": True, "note": "milestone logic in db/queries.rs + stats route", "cat": "retention"},
    {"title": "Seamless Next Up: auto-load 'Next Best Match' at end of chapter/fic",
     "impl": False, "note": "Not found; recommender exists but no auto-next-up", "cat": "discovery"},
    {"title": "Chapter Drop Alerts: poll FanFicFare for bookmarked WIP updates, email/webhook",
     "impl": True, "note": "notify_work_followers + notifications table", "cat": "retention"},
    {"title": "Curator Badges: suggest tags, earn points, display badges (Master Tagger, Trope Hunter)",
     "impl": True, "note": "badge_definitions + curator routes", "cat": "community"},

    # --- Phase 1 Core Discovery ---
    {"title": "Backfill main_char_attr tag scores for existing archive",
     "impl": True, "note": "backfill-scores bin shipped", "cat": "search"},
    {"title": "Fuzzy Search via pg_trgm (typo tolerance: 'Hary Pottr' finds 'Harry Potter')",
     "impl": True, "note": "migration 012 + word_similarity fuzzy fallback", "cat": "search"},
    {"title": "Immutable Cache Headers for hashed SPA assets",
     "impl": True, "note": "CacheHeadersLayer shipped (NEXT.md 8)", "cat": "perf"},

    # --- Phase 2 Hook/Retention ---
    {"title": "Trope/Vibe Browser & Rabbit Holes (GET /api/tropes, /tropes route, More like this)",
     "impl": True, "note": "tropes route shipped (217f13e)", "cat": "discovery"},
    {"title": "Reading Streaks & Milestones (user_streaks table, navbar flame, milestone toasts)",
     "impl": True, "note": "login_streaks + quests + milestones shipped", "cat": "retention"},
    {"title": "Send-to-Kindle (POST /api/send-to-kindle, SMTP email EPUB to Kindle address)",
     "impl": False, "note": "Deferred in STATUS.md — needs SMTP creds; only roadmap UI text", "cat": "utility"},

    # --- Phase 3 Privacy Anti-Bot ---
    {"title": "Anonymous client_id UUID session tracking (no IP logging)",
     "impl": True, "note": "client_id cookie + X-Client-ID, request_log keyed on client_id", "cat": "anti-bot"},
    {"title": "Session & Account tiered rate limits keyed by client_id/user_id",
     "impl": True, "note": "tiered rate limits (download/auth/search) shipped", "cat": "anti-bot"},
    {"title": "Honeypots & form timing traps on register/comment",
     "impl": True, "note": "honeypot + timing traps shipped", "cat": "anti-bot"},
    {"title": "Proof-of-Work challenge for flagged sessions (hashcash)",
     "impl": True, "note": "PoW backend shipped; frontend auto-solve deferred", "cat": "anti-bot"},
    {"title": "Headless flags & admin bot dashboard (client_id prefixes, shadowban)",
     "impl": True, "note": "admin/bots + shadowban shipped", "cat": "anti-bot"},
    {"title": "PoW frontend auto-solve (browser JS computes nonce on 429)",
     "impl": False, "note": "Deferred in STATUS.md — API ready, JS not wired", "cat": "anti-bot"},

    # --- Omniscient Admin Dashboard plan ---
    {"title": "Command Center: realtime ingestion ticker + heartbeat sparklines + resource gauges",
     "impl": True, "note": "Command Center shipped (efeb076)", "cat": "admin"},
    {"title": "Ingestion & Scraper Intelligence: domain health matrix, failed-ingestion graveyard, retry",
     "impl": False, "note": "Not found in code", "cat": "admin"},
    {"title": "Archive Taxonomy: tag galaxy graph, tag hygiene queue (typo clusters), curator workbench",
     "impl": False, "note": "curator routes exist; no tag galaxy/hygiene queue", "cat": "admin"},
    {"title": "Search Analytics: zero-result queries, typo-tolerance efficacy, trope popularity index",
     "impl": True, "note": "search_queries log + /api/admin/search-analytics shipped", "cat": "admin"},
    {"title": "Behavioral Security: bot score leaderboard, PoW telemetry, rate-limit intercepts, honeypot catches",
     "impl": True, "note": "admin/bots + shadowban + realtime shipped", "cat": "admin"},
    {"title": "User & Community Management: user search, moderation queue, role management, streak analytics",
     "impl": True, "note": "user mgmt + moderation partially; role mgmt exists", "cat": "admin"},
    {"title": "Product Consensus: Elo leaderboard + controversy scatter + raw suggestion drill-down",
     "impl": True, "note": "admin/consensus shipped (a3fc49f)", "cat": "admin"},

    # --- Roadmap Consensus Engine ---
    {"title": "Roadmap consensus: semantic clustering (pgvector), MaxDiff arena voting, Elo ranking",
     "impl": True, "note": "migration 011 + roadmap routes + /roadmap UI shipped", "cat": "consensus"},
    {"title": "Cold-start seed of 10-15 admin-suggested features in feature_clusters",
     "impl": True, "note": "61 clusters seeded (758fbbc)", "cat": "consensus"},
    {"title": "Roadmap: 'Mark as Implemented' action + notify suggester, split-cluster admin tool",
     "impl": False, "note": "no mark-implemented/split in code yet", "cat": "consensus"},

    # --- Embeddings / Auto-tagger plan ---
    {"title": "Auto-tagger: zero-shot tag classification from summary+first chapter (machine-suggested tags)",
     "impl": False, "note": "no is_machine_suggested column", "cat": "discovery"},
    {"title": "Cross-platform deduplication via embedding similarity (unified works)",
     "impl": False, "note": "unified_works exists but title/author based; no embedding dedupe", "cat": "discovery"},
    {"title": "'Vibe' semantic search (embedding-based concept search toggle)",
     "impl": False, "note": "no search_by_embedding exposed", "cat": "search"},
    {"title": "Auto-trigger warnings: detect sensitive content in chapters via embeddings",
     "impl": False, "note": "not present", "cat": "safety"},
    {"title": "Implicit vibe recommendations ('Similar Pacing & Prose', ignoring fandom)",
     "impl": False, "note": "precomputed_recommendations exists; no prose-similarity", "cat": "discovery"},
    {"title": "'Find that specific scene': chapter-level embedding search",
     "impl": False, "note": "no fic_chapters_embeddings table", "cat": "search"},

    # --- Translation plan ---
    {"title": "Auto-translation: NLLB local translation of chapters (background queue, lazy on first read)",
     "impl": False, "note": "chapter_translations is crowdsourced only; no NLLB pipeline", "cat": "translation"},
    {"title": "Eager metadata translation (title+summary into en/es/zh) + language detection",
     "impl": False, "note": "no language detection on fic_info", "cat": "translation"},
    {"title": "Crowdsourced translation refinement: side-by-side editor, versions, votes, reputation",
     "impl": True, "note": "work_translations + chapter_translations + locales routes shipped", "cat": "translation"},

    # --- Search engine upgrade plan ---
    {"title": "Tag-type exclusion & 'Strict Gen' mode (hide relationships / no ships)",
     "impl": False, "note": "no exclude_tag_types / strict_gen in SearchParams", "cat": "search"},
    {"title": "Native boolean search via websearch_to_tsquery + ts_headline highlighting",
     "impl": False, "note": "plainto_tsquery still used", "cat": "search"},
    {"title": "Hybrid FTS+vector search via Reciprocal Rank Fusion (RRF)",
     "impl": False, "note": "not present", "cat": "search"},
    {"title": "Tag autocomplete endpoint with usage counts",
     "impl": False, "note": "not found", "cat": "search"},
    {"title": "Dynamic facet counts within current result set",
     "impl": False, "note": "not found", "cat": "search"},
    {"title": "'Hide read' / 'Hide bookmarked' toggles",
     "impl": False, "note": "not found", "cat": "search"},
    {"title": "Time-decayed trending sort (Hacker-News gravity)",
     "impl": True, "note": "trending route exists (trending.rs)", "cat": "search"},
    {"title": "Chaos-monkey search tests (quote abuser, emoji spam, facet bomber)",
     "impl": False, "note": "not present", "cat": "search"},

    # --- Sprint feedback plan (utility/reading) ---
    {"title": "Batch & Series Downloads (author page, series, bookmarks as ZIP)",
     "impl": True, "note": "download_series_handler + batch author download shipped", "cat": "utility"},
    {"title": "Broader scraper support (RoyalRoad native, Wattpad/Quotev via FanFicFare)",
     "impl": True, "note": "RoyalRoad source id 8; FanFicFare fallback handles Wattpad/Quotev", "cat": "scraper"},
    {"title": "Built-in web reader with typography, dark mode, scroll memory",
     "impl": True, "note": "reader route + /read shipped", "cat": "reading"},
    {"title": "Following feed page (new chapters from tracked authors/works)",
     "impl": True, "note": "feed route + follows shipped", "cat": "social"},
    {"title": "Personalised homepage 'For You' carousel (bookmark-cooccurrence based)",
     "impl": True, "note": "precomputed_recommendations + recommender", "cat": "discovery"},
    {"title": "Download queue + progress (cancel/resume)",
     "impl": False, "note": "not found", "cat": "utility"},
    {"title": "Offline reading (PWA)",
     "impl": False, "note": "not found in frontend", "cat": "reading"},
    {"title": "Import/export bookmarks (AO3 CSV, no lock-in)",
     "impl": True, "note": "export_bookmarks_csv + import_bookmarks_csv + frontend shipped (a87e3d8)", "cat": "utility"},
    {"title": "Default preferences (format, tags to exclude, always series)",
     "impl": False, "note": "not found", "cat": "utility"},
    {"title": "Data export/backup button",
     "impl": True, "note": "OWNED by sibling kanban task t_b8068ac1 (feat/user-data-export) — yield lane", "cat": "utility"},
    {"title": "Public community shelves (curated lists)",
     "impl": True, "note": "shelves + opds_shelves + public shelves", "cat": "community"},
    {"title": "Simple comment likes + reply notifications",
     "impl": True, "note": "comments route + notifications", "cat": "community"},
    {"title": "Ratings & short reviews (5-star + 'why I recommend it')",
     "impl": True, "note": "work_ratings + comments", "cat": "community"},
    {"title": "Admin: bulk actions (re-scrape author, re-tag batch)",
     "impl": False, "note": "not found", "cat": "admin"},
    {"title": "Import from other FicHub instances / fichub.net migration tool",
     "impl": False, "note": "not found", "cat": "utility"},
    {"title": "Search my library (within bookmarks/shelves)",
     "impl": False, "note": "not found", "cat": "search"},
    {"title": "Data submission for stories FicHub can't find (manual URL submit)",
     "impl": True, "note": "upload route + manual uploads shipped", "cat": "utility"},
]
