// fichub QA issue generator — emits a fixer-ready ISSUES.md from the bug queue.
// suspected_files come from a verified grep-derived route→file map (ground truth),
// NOT from the local LLM (which hallucinates paths).
// Usage: node qa/gen-issues.js
import { createRequire } from 'module';
import path from 'path';
import { execSync } from 'child_process';
import fs from 'fs';

const require = createRequire(import.meta.url);
const sqlite3 = require('better-sqlite3');

const ROOT = path.resolve(import.meta.dirname, '..');
const DB_PATH = process.env.QA_DB || path.join(ROOT, 'qa', 'bugs.db');
const OUT = path.join(ROOT, 'qa', 'reports', 'ISSUES.md');
const db = new sqlite3(DB_PATH);
// triage column only exists after qa/triage.js has run; tolerate fresh DBs
try { db.prepare('SELECT triage FROM bugs LIMIT 1').get(); } catch {
  try { db.exec('ALTER TABLE bugs ADD COLUMN triage TEXT'); } catch {}
}

// Verified source map: route/fingerprint → real files (checked with grep below).
const SOURCE_MAP = [
  { match: /leaderboard|mismatched types|i16/, files: ['src/db/queries.rs', 'src/routes/badges.rs'], area: 'leaderboard' },
  { match: /opds\/shelves|OPDS/, files: ['src/routes/opds/shelves.rs', 'src/server.rs'], area: 'opds' },
];

function resolveFiles(bug) {
  for (const m of SOURCE_MAP) {
    if (m.match.test(bug.fingerprint + ' ' + bug.title + ' ' + (bug.route || ''))) {
      // verify each file exists
      return m.files.filter(f => fs.existsSync(path.join(ROOT, f)));
    }
  }
  return [];
}

function severityLabel(s) {
  return { p0: 'P0 / Critical', p1: 'P1 / High', p2: 'P2 / Medium', p3: 'P3 / Low' }[s] || s;
}

const bugs = db.prepare(`
  SELECT id, fingerprint, title, severity, category, route, method, status_code, occurrences, evidence_json, triage, first_seen_run, last_seen_run, repro_command, suspected_files_json
  FROM bugs WHERE status NOT IN ('fixed','wontfix','duplicate','closed-false-positive')
  ORDER BY CASE severity WHEN 'p0' THEN 1 WHEN 'p1' THEN 2 WHEN 'p2' THEN 3 ELSE 4 END, id
`).all();

let md = `# FicHub Bug Queue — ${new Date().toISOString().slice(0, 10)}\n\n`;
md += `Generated by qa/ harness (deterministic checks + local LLM triage).\n`;
md += `Queue DB: qa/bugs.db · Re-run: \`node qa/run.js && node qa/triage.js && node qa/gen-issues.js\`\n\n`;
md += `## Summary\n\n| Severity | Count |\n|----------|-------|\n`;
for (const s of ['p0', 'p1', 'p2', 'p3']) {
  const n = bugs.filter(b => b.severity === s).length;
  if (n) md += `| ${severityLabel(s)} | ${n} |\n`;
}
md += `\n---\n\n`;

for (const b of bugs) {
  const files = resolveFiles(b);
  const ev = (() => { try { return JSON.parse(b.evidence_json || '{}'); } catch { return {}; } })();
  let triage = null;
  if (b.triage) {
    try {
      // The local LLM often wraps JSON in markdown or nests it; extract deepest object.
      const m = b.triage.match(/\{[\s\S]*\}/);
      const raw = m ? m[0] : b.triage;
      let parsed = JSON.parse(raw);
      // unwrap single nesting level ("summary" containing another JSON blob)
      while (parsed.summary && parsed.summary.includes('"summary"')) {
        const inner = parsed.summary.match(/\{[\s\S]*\}/);
        if (!inner) break;
        const deeper = JSON.parse(inner[0]);
        parsed = { ...parsed, ...deeper };
      }
      triage = parsed;
    } catch {}
  }

  md += `## BUG-${String(b.id).padStart(4, '0')} — ${b.title}\n\n`;
  md += `- **Severity:** ${severityLabel(b.severity)}\n`;
  md += `- **Category:** ${b.category}\n`;
  md += `- **Status:** open\n`;
  md += `- **First seen (run):** ${b.first_seen_run || '?'} · **Last seen (run):** ${b.last_seen_run || '?'} · **Occurrences:** ${b.occurrences}\n`;
  md += `- **Route:** \`${b.route}\` ${b.method ? '· Method: ' + b.method : ''} ${b.status_code ? '· Status: ' + b.status_code : ''}\n`;
  md += `- **Affected URLs:** ${b.route || '(backend)'}\n`;
  md += `- **Fingerprint:** \`${b.fingerprint}\`\n`;
  md += `- **Suspected files:** ${files.length ? files.map(f => '`' + f + '`').join(', ') : 'unknown — check evidence'}\n`;
  if (triage) {
    const cleanSummary = (triage.summary || '')
      .replace(/^Here is the bug report in JSON format:\s*/i, '')
      .replace(/^Here is the JSON output for the bug report:\s*/i, '')
      .replace(/```json|```/g, '')
      .replace(/\s+/g, ' ')
      .trim()
      .split('. ').slice(0, 2).join('. ');
    // If the small model produced garbage, fall back to deterministic description.
    const usable = cleanSummary && !cleanSummary.includes('{') && !cleanSummary.includes('"summary"') && !cleanSummary.startsWith('{');
    if (usable) md += `- **Summary (local triage):** ${cleanSummary}\n`;
    else md += `- **Summary (deterministic):** ${b.category} finding on ${b.route}${b.status_code ? ' — HTTP ' + b.status_code : ''}. See evidence.\n`;
    if (triage.likely_cause) md += `- **Likely cause (triage):** ${String(triage.likely_cause).replace(/```/g, '').slice(0, 160)}\n`;
  }
  md += `\n**Evidence:**\n\n\`\`\`json\n${JSON.stringify(ev, null, 2).slice(0, 800)}\n\`\`\`\n\n`;
  md += `**Repro:** hit the route as in evidence; for browser findings, load the affected URL and check console/network.\n\n`;
  md += `**To fix:** (a) add a failing test, (b) smallest change, (c) verify with qa/run.js that this fingerprint disappears, (d) keep the test.\n\n---\n\n`;
}

fs.writeFileSync(OUT, md);
console.log(`wrote ${OUT} (${bugs.length} issues)`);
